spring:
  profiles:
    active: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.231.56.252:3306/getickdb
    username: getick
    password: getick.cn

    # Tomcat specifics
    tomcat:
        initialSize: 1
        min-idle: 1
        max-idle: 20
        max-wait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false