spring:
  profiles:
    active: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://149.28.198.111:3306
    username: ssrco
    password: ikuacc

    # Tomcat specifics
    tomcat:
        initialSize: 1
        min-idle: 1
        max-idle: 20
        max-wait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false